services:
  - type: web
    name: shopscanner-backend
    runtime: docker
    rootDir: backend
    # buildCommand and startCommand are not needed for docker runtime

    envVars:
      - key: PORT
        value: 10000
      - key: DELAY_MS
        value: 2000
      - key: MAX_RESULTS
        value: 50
      - key: NODE_ENV
        value: production
